services:
  reservation-service:
    image: "nestjs-restaurant/reservation-service"
    restart: always
    ports:
      - 3003:3000
    depends_on:
      - mongo_db_reservation
    networks:
      - nestjs-restaurant-network
  mongo_db_reservation:
    image: "mongo:4.4.15"
    restart: always
    ports:
      - 27021:27017
    networks:
      - nestjs-restaurant-network
networks:
  nestjs-restaurant-network:
    driver: bridge
